import "server-only";
import { ANTHROPIC_MODELS, getAnthropic } from "@/lib/ai/anthropic";

/**
 * Feature-highlight extractor for the bottom feature row of post templates.
 *
 * Reads a listing's `public_remarks` (the MLS-provided marketing description)
 * and returns ONE short ALL-CAPS phrase — 1 to 3 words — that captures the
 * most marketable feature. Examples from the brokerage's existing FB posts:
 *
 *   "AWESOME sunset views overlooking the intracoastal waterway"
 *     → "SUNSET VIEWS"
 *   "Open-concept layout, multiple decks, a fireplace, and incredible water views"
 *     → "WATER VIEWS"
 *   "Gourmet kitchen with quartz countertops, stainless appliances..."
 *     → "GOURMET KITCHEN"
 *
 * The result populates the third column of the bottom feature row, e.g.
 *   `4 BEDROOM | 2.5 BATHROOM | SUNSET VIEWS`
 *
 * Why a single short call:
 *   • Costs ~1k input tokens, ~10 output tokens. Pennies per render.
 *   • Cached on `generated_posts.template_props.feature_highlight` so we
 *     never re-call for the same post. Studio admins can also hand-edit
 *     the value via the canvas text layer.
 *
 * When the AI is unavailable (no API key configured) we fall back to a
 * deterministic heuristic — pull the first capitalized noun phrase from
 * the remarks. Imperfect but predictable.
 */

const MAX_REMARKS_CHARS = 1500;
const MAX_PHRASE_WORDS = 3;

export interface FeatureExtractorInput {
  /** Listing's public marketing remarks (from MLS feed). */
  remarks: string | null | undefined;
  /** Optional: extra context (e.g., property type) for richer prompts. */
  propertyType?: string | null;
}

export interface FeatureExtractorResult {
  /** The marketable phrase, ALL CAPS, ≤3 words. Null when nothing extractable. */
  phrase: string | null;
  /** "ai" when generated by Claude; "fallback" when heuristic; "skipped" when no input. */
  source: "ai" | "fallback" | "skipped";
}

export async function extractFeatureHighlight(
  input: FeatureExtractorInput,
): Promise<FeatureExtractorResult> {
  const raw = (input.remarks ?? "").trim();
  if (!raw) return { phrase: null, source: "skipped" };

  const truncated =
    raw.length > MAX_REMARKS_CHARS ? raw.slice(0, MAX_REMARKS_CHARS) : raw;

  const anthropic = await getAnthropic();
  if (!anthropic) {
    return { phrase: heuristicFallback(truncated), source: "fallback" };
  }

  try {
    // why: tight prompt for a tight output. Examples anchor the model on the
    // shape we want (ALL CAPS, ≤3 words, marketable). Sonnet is fast + cheap
    // and the task is well-bounded — Opus would be overkill.
    const response = await anthropic.messages.create({
      model: ANTHROPIC_MODELS.sonnet,
      max_tokens: 20,
      system:
        "You write short, punchy real-estate marketing tags. Given a listing description, output ONE marketable phrase that captures the single most distinctive selling feature of the property. Format: ALL CAPS, exactly 1 to 3 words, no punctuation, no quotes. Examples: SUNSET VIEWS, WATERFRONT, GOURMET KITCHEN, PRIVATE DOCK, BEACH BLOCK, NEW CONSTRUCTION, GOLF COURSE, OCEAN VIEWS, CHEF'S KITCHEN, MOUNTAIN VIEWS. Never invent features that aren't in the description. If the description is generic, output the property type instead (e.g., TOWNHOUSE, SINGLE FAMILY).",
      messages: [
        {
          role: "user",
          content: `Listing description:\n${truncated}${input.propertyType ? `\n\nProperty type: ${input.propertyType}` : ""}\n\nReturn just the phrase, nothing else.`,
        },
      ],
    });

    const text = response.content
      .map((b) => (b.type === "text" ? b.text : ""))
      .join(" ")
      .trim();

    const cleaned = sanitizePhrase(text);
    if (!cleaned) {
      return { phrase: heuristicFallback(truncated), source: "fallback" };
    }
    return { phrase: cleaned, source: "ai" };
  } catch (e) {
    console.warn(
      "[feature-extractor] Claude call failed, falling back:",
      e instanceof Error ? e.message : String(e),
    );
    return { phrase: heuristicFallback(truncated), source: "fallback" };
  }
}

/**
 * Strip junk and enforce the format invariants:
 *   • ALL CAPS
 *   • 1 to 3 words
 *   • No punctuation except apostrophes (CHEF'S KITCHEN)
 *   • No surrounding quotes
 */
function sanitizePhrase(raw: string): string | null {
  let s = raw.trim();
  // Strip wrapping quotes Claude sometimes adds.
  s = s.replace(/^["'`]+|["'`]+$/g, "");
  // Strip trailing punctuation.
  s = s.replace(/[.,!?;:]+$/g, "");
  if (!s) return null;
  s = s.toUpperCase();
  const words = s.split(/\s+/).filter(Boolean);
  if (words.length === 0) return null;
  if (words.length > MAX_PHRASE_WORDS) {
    return words.slice(0, MAX_PHRASE_WORDS).join(" ");
  }
  return words.join(" ");
}

/**
 * Heuristic fallback used when Claude is unavailable (no API key) or errors.
 * Pulls the first capitalized noun-phrase-ish sequence from the remarks.
 * Imperfect but deterministic — better than returning null and showing a
 * blank feature column.
 */
function heuristicFallback(remarks: string): string | null {
  // why: search for marketing keywords first (verbose but bounded) — these
  // appear frequently in NJ shore listings and produce decent phrases.
  const KEYWORD_PATTERNS: Array<{ pattern: RegExp; phrase: string }> = [
    { pattern: /\bwaterfront\b/i, phrase: "WATERFRONT" },
    { pattern: /\boceanfront\b/i, phrase: "OCEANFRONT" },
    { pattern: /\bbay\s*front\b/i, phrase: "BAY FRONT" },
    { pattern: /\bsunset\s+view/i, phrase: "SUNSET VIEWS" },
    { pattern: /\bocean\s+view/i, phrase: "OCEAN VIEWS" },
    { pattern: /\bwater\s+view/i, phrase: "WATER VIEWS" },
    { pattern: /\bbay\s+view/i, phrase: "BAY VIEWS" },
    { pattern: /\bgolf\s+course/i, phrase: "GOLF COURSE" },
    { pattern: /\bbeach\s+block\b/i, phrase: "BEACH BLOCK" },
    { pattern: /\bnewly?\s+constructed?\b/i, phrase: "NEW CONSTRUCTION" },
    { pattern: /\bnew\s+build\b/i, phrase: "NEW CONSTRUCTION" },
    { pattern: /\bgourmet\s+kitchen/i, phrase: "GOURMET KITCHEN" },
    { pattern: /\bchef'?s?\s+kitchen/i, phrase: "CHEF'S KITCHEN" },
    { pattern: /\bprivate\s+dock\b/i, phrase: "PRIVATE DOCK" },
    { pattern: /\bprivate\s+pool\b/i, phrase: "PRIVATE POOL" },
    { pattern: /\bin-?ground\s+pool\b/i, phrase: "POOL" },
    { pattern: /\bcustom\s+built\b/i, phrase: "CUSTOM BUILT" },
    { pattern: /\bturnkey\b/i, phrase: "TURNKEY" },
    { pattern: /\bfully\s+renovated\b/i, phrase: "FULLY RENOVATED" },
    { pattern: /\bopen\s+concept\b/i, phrase: "OPEN CONCEPT" },
    { pattern: /\bmultiple\s+decks\b/i, phrase: "MULTIPLE DECKS" },
    { pattern: /\brooftop\s+deck\b/i, phrase: "ROOFTOP DECK" },
  ];
  for (const { pattern, phrase } of KEYWORD_PATTERNS) {
    if (pattern.test(remarks)) return phrase;
  }
  return null;
}
