/**
 * Just Listed · Hero Editorial · Square 1:1 (1080×1080)
 * ------------------------------------------------------
 *
 * Hero photo fills the frame. A dark scrim covers the bottom ~35% so the
 * eyebrow + address + price + stats are legible regardless of photo content.
 * Gold accent on the eyebrow rule and price for brand recognition.
 *
 * Mirrors the visual intent of the existing V1 "Hero Editorial" variant
 * (variant v1) at square format. This template is hand-authored for Step 2
 * to validate the editor end-to-end against real listing data.
 *
 * Layer stacking (low z → high z):
 *   z=0   hero_photo            full-bleed listing photo, cover-fit
 *   z=1   dark_overlay          black rect at 65% opacity over bottom band
 *   z=2   eyebrow_rule          short gold rule above the JUST LISTED label
 *   z=3   status_label          "JUST LISTED" eyebrow text
 *   z=4   address_line          street address
 *   z=5   city_state_zip        city/state/zip line
 *   z=6   price                 list price (gold)
 *   z=7   beds_baths            stats row
 *   z=8   office_footer         "CENTURY 21 ALLIANCE"
 *   z=9   mls_number            small grey MLS code in corner
 */

import type { CanvasTemplateSchema } from "../types";
import { ALLIANCE_COLORS, ALLIANCE_FONTS } from "./tokens";

export const justListedHeroSquare: CanvasTemplateSchema = {
  id: "canvas_just_listed_v1_square",
  name: "Just Listed · Hero Editorial · Square",
  description:
    "Hero photo fills the frame with a dark scrim and gold-accented type stacked over the bottom third. Best when the photo is the story.",
  category: "just_listed",
  variant: "v1",
  format: "square_1x1",
  width: 1080,
  height: 1080,
  backgroundColor: "#FFFFFF",
  backgroundImage: null,
  updatedAt: "2026-05-14T00:00:00Z",
  schemaVersion: 1,
  layers: [
    // ----- hero photo (fills frame) -----
    {
      kind: "image",
      id: "layer_hero_photo",
      name: "Hero photo",
      left: 0,
      top: 0,
      width: 1080,
      height: 1080,
      angle: 0,
      opacity: 1,
      z: 0,
      visible: true,
      locked: false,
      src: null,
      boundField: "hero_photo",
      objectFit: "cover",
      crossOrigin: "anonymous",
      cornerRadius: 0,
      borderColor: "transparent",
      borderWidth: 0,
    },
    // ----- dark scrim over bottom band -----
    {
      kind: "shape",
      id: "layer_dark_overlay",
      name: "Dark overlay",
      left: 0,
      top: 700,
      width: 1080,
      height: 380,
      angle: 0,
      opacity: 0.65,
      z: 1,
      visible: true,
      locked: false,
      shapeType: "rect",
      fill: ALLIANCE_COLORS.blackAt65,
      stroke: "",
      strokeWidth: 0,
      cornerRadius: 0,
      strokeDashArray: [],
    },
    // ----- gold rule above eyebrow -----
    {
      kind: "shape",
      id: "layer_eyebrow_rule",
      name: "Gold accent rule",
      left: 60,
      top: 60,
      width: 56,
      height: 4,
      angle: 0,
      opacity: 1,
      z: 2,
      visible: true,
      locked: false,
      shapeType: "rect",
      fill: ALLIANCE_COLORS.gold500,
      stroke: "",
      strokeWidth: 0,
      cornerRadius: 2,
      strokeDashArray: [],
    },
    // ----- JUST LISTED eyebrow label -----
    {
      kind: "text",
      id: "layer_status_label",
      name: "Status label",
      left: 60,
      top: 78,
      width: 400,
      height: 36,
      angle: 0,
      opacity: 1,
      z: 3,
      visible: true,
      locked: false,
      text: "JUST LISTED",
      boundField: "status_label",
      fontFamily: ALLIANCE_FONTS.bodySans,
      fontSize: 24,
      fontWeight: 700,
      fontStyle: "normal",
      fill: ALLIANCE_COLORS.white,
      textAlign: "left",
      lineHeight: 1.1,
      charSpacing: 300,
      underline: false,
      linethrough: false,
      editable: true,
    },
    // ----- address line 1 -----
    {
      kind: "text",
      id: "layer_address_line",
      name: "Address",
      left: 60,
      top: 760,
      width: 960,
      height: 70,
      angle: 0,
      opacity: 1,
      z: 4,
      visible: true,
      locked: false,
      text: "117 E Maple Ave",
      boundField: "address_line1",
      fontFamily: ALLIANCE_FONTS.displaySerif,
      fontSize: 56,
      fontWeight: 700,
      fontStyle: "normal",
      fill: ALLIANCE_COLORS.white,
      textAlign: "left",
      lineHeight: 1.1,
      charSpacing: 0,
      underline: false,
      linethrough: false,
      editable: true,
    },
    // ----- city, state, zip -----
    {
      kind: "text",
      id: "layer_city_state_zip",
      name: "City · State · Zip",
      left: 60,
      top: 840,
      width: 960,
      height: 36,
      angle: 0,
      opacity: 1,
      z: 5,
      visible: true,
      locked: false,
      text: "Wildwood, NJ 08260",
      boundField: "city_state_zip",
      fontFamily: ALLIANCE_FONTS.bodySans,
      fontSize: 24,
      fontWeight: 400,
      fontStyle: "normal",
      fill: ALLIANCE_COLORS.whiteDim,
      textAlign: "left",
      lineHeight: 1.2,
      charSpacing: 100,
      underline: false,
      linethrough: false,
      editable: true,
    },
    // ----- price (gold, prominent) -----
    {
      kind: "text",
      id: "layer_price",
      name: "Price",
      left: 60,
      top: 900,
      width: 700,
      height: 90,
      angle: 0,
      opacity: 1,
      z: 6,
      visible: true,
      locked: false,
      text: "$929,000",
      boundField: "price",
      fontFamily: ALLIANCE_FONTS.displaySerif,
      fontSize: 72,
      fontWeight: 800,
      fontStyle: "normal",
      fill: ALLIANCE_COLORS.gold500,
      textAlign: "left",
      lineHeight: 1.05,
      charSpacing: 0,
      underline: false,
      linethrough: false,
      editable: true,
    },
    // ----- beds / baths stats row -----
    {
      kind: "text",
      id: "layer_beds_baths",
      name: "Beds · Baths",
      left: 60,
      top: 1010,
      width: 600,
      height: 28,
      angle: 0,
      opacity: 0.95,
      z: 7,
      visible: true,
      locked: false,
      text: "4 BR / 3 BA",
      boundField: "beds_baths",
      fontFamily: ALLIANCE_FONTS.bodySans,
      fontSize: 20,
      fontWeight: 500,
      fontStyle: "normal",
      fill: ALLIANCE_COLORS.white,
      textAlign: "left",
      lineHeight: 1.2,
      charSpacing: 200,
      underline: false,
      linethrough: false,
      editable: true,
    },
    // ----- office footer -----
    {
      kind: "text",
      id: "layer_office_footer",
      name: "Office",
      left: 760,
      top: 1010,
      width: 260,
      height: 28,
      angle: 0,
      opacity: 0.9,
      z: 8,
      visible: true,
      locked: false,
      text: "CENTURY 21 ALLIANCE",
      boundField: "office_name",
      fontFamily: ALLIANCE_FONTS.bodySans,
      fontSize: 14,
      fontWeight: 600,
      fontStyle: "normal",
      fill: ALLIANCE_COLORS.whiteDim,
      textAlign: "right",
      lineHeight: 1.2,
      charSpacing: 300,
      underline: false,
      linethrough: false,
      editable: true,
    },
    // ----- MLS number (tiny) -----
    {
      kind: "text",
      id: "layer_mls_number",
      name: "MLS #",
      left: 760,
      top: 1042,
      width: 260,
      height: 20,
      angle: 0,
      opacity: 0.7,
      z: 9,
      visible: true,
      locked: false,
      text: "MLS #607680",
      boundField: "mls_number",
      fontFamily: ALLIANCE_FONTS.monoNum,
      fontSize: 11,
      fontWeight: 400,
      fontStyle: "normal",
      fill: ALLIANCE_COLORS.whiteDim,
      textAlign: "right",
      lineHeight: 1.2,
      charSpacing: 100,
      underline: false,
      linethrough: false,
      editable: true,
    },
  ],
};
