/**
 * Just Listed · Hero Editorial · Portrait 4:5 (1080×1350)
 * --------------------------------------------------------
 *
 * Vertical sibling of the square template. Same visual language — hero photo
 * fills the frame, dark scrim over the bottom band, gold accent for the
 * eyebrow and price. The portrait format gives us 270px more vertical room
 * than the square; we use it to grow the photo, leaving a similar 35% text
 * band at the bottom (now ~470px instead of ~380px) with looser leading.
 *
 * Use case: Instagram feed where the algorithm boosts 4:5 over 1:1.
 *
 * Layer stack matches the square template — see that file for documentation.
 */

import type { CanvasTemplateSchema } from "../types";
import { ALLIANCE_COLORS, ALLIANCE_FONTS } from "./tokens";

export const justListedHeroPortrait: CanvasTemplateSchema = {
  id: "canvas_just_listed_v1_portrait",
  name: "Just Listed · Hero Editorial · Portrait",
  description:
    "Vertical 4:5 layout optimized for Instagram feed. Hero photo dominates with a dark scrim and gold-accented type along the bottom band.",
  category: "just_listed",
  variant: "v1",
  format: "portrait_4x5",
  width: 1080,
  height: 1350,
  backgroundColor: "#FFFFFF",
  backgroundImage: null,
  updatedAt: "2026-05-14T00:00:00Z",
  schemaVersion: 1,
  layers: [
    {
      kind: "image",
      id: "layer_hero_photo",
      name: "Hero photo",
      left: 0,
      top: 0,
      width: 1080,
      height: 1350,
      angle: 0,
      opacity: 1,
      z: 0,
      visible: true,
      locked: false,
      src: null,
      boundField: "hero_photo",
      objectFit: "cover",
      crossOrigin: "anonymous",
      cornerRadius: 0,
      borderColor: "transparent",
      borderWidth: 0,
    },
    {
      kind: "shape",
      id: "layer_dark_overlay",
      name: "Dark overlay",
      left: 0,
      top: 880,
      width: 1080,
      height: 470,
      angle: 0,
      opacity: 0.65,
      z: 1,
      visible: true,
      locked: false,
      shapeType: "rect",
      fill: ALLIANCE_COLORS.blackAt65,
      stroke: "",
      strokeWidth: 0,
      cornerRadius: 0,
      strokeDashArray: [],
    },
    {
      kind: "shape",
      id: "layer_eyebrow_rule",
      name: "Gold accent rule",
      left: 60,
      top: 60,
      width: 64,
      height: 4,
      angle: 0,
      opacity: 1,
      z: 2,
      visible: true,
      locked: false,
      shapeType: "rect",
      fill: ALLIANCE_COLORS.gold500,
      stroke: "",
      strokeWidth: 0,
      cornerRadius: 2,
      strokeDashArray: [],
    },
    {
      kind: "text",
      id: "layer_status_label",
      name: "Status label",
      left: 60,
      top: 80,
      width: 400,
      height: 36,
      angle: 0,
      opacity: 1,
      z: 3,
      visible: true,
      locked: false,
      text: "JUST LISTED",
      boundField: "status_label",
      fontFamily: ALLIANCE_FONTS.bodySans,
      fontSize: 26,
      fontWeight: 700,
      fontStyle: "normal",
      fill: ALLIANCE_COLORS.white,
      textAlign: "left",
      lineHeight: 1.1,
      charSpacing: 300,
      underline: false,
      linethrough: false,
      editable: true,
    },
    {
      kind: "text",
      id: "layer_address_line",
      name: "Address",
      left: 60,
      top: 960,
      width: 960,
      height: 80,
      angle: 0,
      opacity: 1,
      z: 4,
      visible: true,
      locked: false,
      text: "117 E Maple Ave",
      boundField: "address_line1",
      fontFamily: ALLIANCE_FONTS.displaySerif,
      fontSize: 64,
      fontWeight: 700,
      fontStyle: "normal",
      fill: ALLIANCE_COLORS.white,
      textAlign: "left",
      lineHeight: 1.1,
      charSpacing: 0,
      underline: false,
      linethrough: false,
      editable: true,
    },
    {
      kind: "text",
      id: "layer_city_state_zip",
      name: "City · State · Zip",
      left: 60,
      top: 1055,
      width: 960,
      height: 40,
      angle: 0,
      opacity: 1,
      z: 5,
      visible: true,
      locked: false,
      text: "Wildwood, NJ 08260",
      boundField: "city_state_zip",
      fontFamily: ALLIANCE_FONTS.bodySans,
      fontSize: 26,
      fontWeight: 400,
      fontStyle: "normal",
      fill: ALLIANCE_COLORS.whiteDim,
      textAlign: "left",
      lineHeight: 1.2,
      charSpacing: 100,
      underline: false,
      linethrough: false,
      editable: true,
    },
    {
      kind: "text",
      id: "layer_price",
      name: "Price",
      left: 60,
      top: 1125,
      width: 700,
      height: 100,
      angle: 0,
      opacity: 1,
      z: 6,
      visible: true,
      locked: false,
      text: "$929,000",
      boundField: "price",
      fontFamily: ALLIANCE_FONTS.displaySerif,
      fontSize: 84,
      fontWeight: 800,
      fontStyle: "normal",
      fill: ALLIANCE_COLORS.gold500,
      textAlign: "left",
      lineHeight: 1.05,
      charSpacing: 0,
      underline: false,
      linethrough: false,
      editable: true,
    },
    {
      kind: "text",
      id: "layer_beds_baths",
      name: "Beds · Baths",
      left: 60,
      top: 1255,
      width: 600,
      height: 28,
      angle: 0,
      opacity: 0.95,
      z: 7,
      visible: true,
      locked: false,
      text: "4 BR / 3 BA",
      boundField: "beds_baths",
      fontFamily: ALLIANCE_FONTS.bodySans,
      fontSize: 22,
      fontWeight: 500,
      fontStyle: "normal",
      fill: ALLIANCE_COLORS.white,
      textAlign: "left",
      lineHeight: 1.2,
      charSpacing: 200,
      underline: false,
      linethrough: false,
      editable: true,
    },
    {
      kind: "text",
      id: "layer_office_footer",
      name: "Office",
      left: 720,
      top: 1255,
      width: 300,
      height: 28,
      angle: 0,
      opacity: 0.9,
      z: 8,
      visible: true,
      locked: false,
      text: "CENTURY 21 ALLIANCE",
      boundField: "office_name",
      fontFamily: ALLIANCE_FONTS.bodySans,
      fontSize: 14,
      fontWeight: 600,
      fontStyle: "normal",
      fill: ALLIANCE_COLORS.whiteDim,
      textAlign: "right",
      lineHeight: 1.2,
      charSpacing: 300,
      underline: false,
      linethrough: false,
      editable: true,
    },
    {
      kind: "text",
      id: "layer_mls_number",
      name: "MLS #",
      left: 720,
      top: 1290,
      width: 300,
      height: 20,
      angle: 0,
      opacity: 0.7,
      z: 9,
      visible: true,
      locked: false,
      text: "MLS #607680",
      boundField: "mls_number",
      fontFamily: ALLIANCE_FONTS.monoNum,
      fontSize: 11,
      fontWeight: 400,
      fontStyle: "normal",
      fill: ALLIANCE_COLORS.whiteDim,
      textAlign: "right",
      lineHeight: 1.2,
      charSpacing: 100,
      underline: false,
      linethrough: false,
      editable: true,
    },
  ],
};
