/**
 * Just Listed · Hero Editorial · Story 9:16 (1080×1920)
 * ------------------------------------------------------
 *
 * Story format reads differently than feed: it's swiped through quickly and
 * the top + bottom 15% are "safe zones" where Instagram/TikTok overlay their
 * own UI (profile chip top-left, send arrow bottom-right). We respect those
 * by:
 *   • Pushing the JUST LISTED eyebrow down to top:140 (avoiding the profile UI)
 *   • Keeping the price + stats above bottom:200 (avoiding the swipe-up UI)
 *
 * The dark scrim is taller (800px instead of 470px) to give space for a price
 * + tagline + stats stack that reads at thumbing-speed.
 *
 * Layer stack matches the square template — see that file for documentation.
 */

import type { CanvasTemplateSchema } from "../types";
import { ALLIANCE_COLORS, ALLIANCE_FONTS } from "./tokens";

export const justListedHeroStory: CanvasTemplateSchema = {
  id: "canvas_just_listed_v1_story",
  name: "Just Listed · Hero Editorial · Story",
  description:
    "9:16 vertical optimized for IG/FB/TikTok Stories. Hero photo with a tall dark band along the bottom for type — safe-zones respected top and bottom.",
  category: "just_listed",
  variant: "v1",
  format: "story_9x16",
  width: 1080,
  height: 1920,
  backgroundColor: "#FFFFFF",
  backgroundImage: null,
  updatedAt: "2026-05-14T00:00:00Z",
  schemaVersion: 1,
  layers: [
    {
      kind: "image",
      id: "layer_hero_photo",
      name: "Hero photo",
      left: 0,
      top: 0,
      width: 1080,
      height: 1920,
      angle: 0,
      opacity: 1,
      z: 0,
      visible: true,
      locked: false,
      src: null,
      boundField: "hero_photo",
      objectFit: "cover",
      crossOrigin: "anonymous",
      cornerRadius: 0,
      borderColor: "transparent",
      borderWidth: 0,
    },
    {
      kind: "shape",
      id: "layer_dark_overlay",
      name: "Dark overlay",
      left: 0,
      top: 1120,
      width: 1080,
      height: 800,
      angle: 0,
      opacity: 0.65,
      z: 1,
      visible: true,
      locked: false,
      shapeType: "rect",
      fill: ALLIANCE_COLORS.blackAt65,
      stroke: "",
      strokeWidth: 0,
      cornerRadius: 0,
      strokeDashArray: [],
    },
    {
      kind: "shape",
      id: "layer_eyebrow_rule",
      name: "Gold accent rule",
      left: 80,
      top: 140,
      width: 72,
      height: 4,
      angle: 0,
      opacity: 1,
      z: 2,
      visible: true,
      locked: false,
      shapeType: "rect",
      fill: ALLIANCE_COLORS.gold500,
      stroke: "",
      strokeWidth: 0,
      cornerRadius: 2,
      strokeDashArray: [],
    },
    {
      kind: "text",
      id: "layer_status_label",
      name: "Status label",
      left: 80,
      top: 165,
      width: 500,
      height: 44,
      angle: 0,
      opacity: 1,
      z: 3,
      visible: true,
      locked: false,
      text: "JUST LISTED",
      boundField: "status_label",
      fontFamily: ALLIANCE_FONTS.bodySans,
      fontSize: 32,
      fontWeight: 700,
      fontStyle: "normal",
      fill: ALLIANCE_COLORS.white,
      textAlign: "left",
      lineHeight: 1.1,
      charSpacing: 300,
      underline: false,
      linethrough: false,
      editable: true,
    },
    {
      kind: "text",
      id: "layer_address_line",
      name: "Address",
      left: 80,
      top: 1220,
      width: 920,
      height: 100,
      angle: 0,
      opacity: 1,
      z: 4,
      visible: true,
      locked: false,
      text: "117 E Maple Ave",
      boundField: "address_line1",
      fontFamily: ALLIANCE_FONTS.displaySerif,
      fontSize: 76,
      fontWeight: 700,
      fontStyle: "normal",
      fill: ALLIANCE_COLORS.white,
      textAlign: "left",
      lineHeight: 1.1,
      charSpacing: 0,
      underline: false,
      linethrough: false,
      editable: true,
    },
    {
      kind: "text",
      id: "layer_city_state_zip",
      name: "City · State · Zip",
      left: 80,
      top: 1340,
      width: 920,
      height: 44,
      angle: 0,
      opacity: 1,
      z: 5,
      visible: true,
      locked: false,
      text: "Wildwood, NJ 08260",
      boundField: "city_state_zip",
      fontFamily: ALLIANCE_FONTS.bodySans,
      fontSize: 32,
      fontWeight: 400,
      fontStyle: "normal",
      fill: ALLIANCE_COLORS.whiteDim,
      textAlign: "left",
      lineHeight: 1.2,
      charSpacing: 100,
      underline: false,
      linethrough: false,
      editable: true,
    },
    {
      kind: "text",
      id: "layer_price",
      name: "Price",
      left: 80,
      top: 1430,
      width: 920,
      height: 130,
      angle: 0,
      opacity: 1,
      z: 6,
      visible: true,
      locked: false,
      text: "$929,000",
      boundField: "price",
      fontFamily: ALLIANCE_FONTS.displaySerif,
      fontSize: 108,
      fontWeight: 800,
      fontStyle: "normal",
      fill: ALLIANCE_COLORS.gold500,
      textAlign: "left",
      lineHeight: 1.05,
      charSpacing: 0,
      underline: false,
      linethrough: false,
      editable: true,
    },
    {
      kind: "text",
      id: "layer_beds_baths",
      name: "Beds · Baths",
      left: 80,
      top: 1590,
      width: 600,
      height: 36,
      angle: 0,
      opacity: 0.95,
      z: 7,
      visible: true,
      locked: false,
      text: "4 BR / 3 BA",
      boundField: "beds_baths",
      fontFamily: ALLIANCE_FONTS.bodySans,
      fontSize: 28,
      fontWeight: 500,
      fontStyle: "normal",
      fill: ALLIANCE_COLORS.white,
      textAlign: "left",
      lineHeight: 1.2,
      charSpacing: 200,
      underline: false,
      linethrough: false,
      editable: true,
    },
    // ----- footer block — pushed up to clear story bottom-safe zone (~200px) -----
    {
      kind: "text",
      id: "layer_office_footer",
      name: "Office",
      left: 80,
      top: 1700,
      width: 920,
      height: 32,
      angle: 0,
      opacity: 0.9,
      z: 8,
      visible: true,
      locked: false,
      text: "CENTURY 21 ALLIANCE",
      boundField: "office_name",
      fontFamily: ALLIANCE_FONTS.bodySans,
      fontSize: 18,
      fontWeight: 600,
      fontStyle: "normal",
      fill: ALLIANCE_COLORS.whiteDim,
      textAlign: "left",
      lineHeight: 1.2,
      charSpacing: 300,
      underline: false,
      linethrough: false,
      editable: true,
    },
    {
      kind: "text",
      id: "layer_mls_number",
      name: "MLS #",
      left: 80,
      top: 1740,
      width: 920,
      height: 24,
      angle: 0,
      opacity: 0.7,
      z: 9,
      visible: true,
      locked: false,
      text: "MLS #607680",
      boundField: "mls_number",
      fontFamily: ALLIANCE_FONTS.monoNum,
      fontSize: 14,
      fontWeight: 400,
      fontStyle: "normal",
      fill: ALLIANCE_COLORS.whiteDim,
      textAlign: "left",
      lineHeight: 1.2,
      charSpacing: 100,
      underline: false,
      linethrough: false,
      editable: true,
    },
  ],
};
