// Auto-generated by `supabase gen types typescript` (via Supabase MCP).
// Re-run after schema changes.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  __InternalSupabase: { PostgrestVersion: "14.5" };
  public: {
    Tables: {
      api_credentials: {
        Row: {
          created_at: string;
          credentials: Json;
          id: string;
          is_active: boolean;
          last_validated_at: string | null;
          platform: Database["public"]["Enums"]["credential_platform"];
          updated_at: string;
        };
        Insert: {
          created_at?: string;
          credentials?: Json;
          id?: string;
          is_active?: boolean;
          last_validated_at?: string | null;
          platform: Database["public"]["Enums"]["credential_platform"];
          updated_at?: string;
        };
        Update: {
          created_at?: string;
          credentials?: Json;
          id?: string;
          is_active?: boolean;
          last_validated_at?: string | null;
          platform?: Database["public"]["Enums"]["credential_platform"];
          updated_at?: string;
        };
        Relationships: [];
      };
      notifications: {
        Row: {
          created_at: string;
          id: string;
          is_read: boolean;
          message: string | null;
          metadata: Json;
          title: string;
          type: string;
          updated_at: string;
          user_id: string;
        };
        Insert: {
          created_at?: string;
          id?: string;
          is_read?: boolean;
          message?: string | null;
          metadata?: Json;
          title: string;
          type: string;
          updated_at?: string;
          user_id: string;
        };
        Update: {
          created_at?: string;
          id?: string;
          is_read?: boolean;
          message?: string | null;
          metadata?: Json;
          title?: string;
          type?: string;
          updated_at?: string;
          user_id?: string;
        };
        Relationships: [];
      };
      posts: {
        Row: {
          caption: string | null;
          created_at: string;
          id: string;
          last_synced_at: string | null;
          media_type: Database["public"]["Enums"]["media_type"] | null;
          media_url: string | null;
          metrics: Json;
          mls_number_parsed: string | null;
          permalink: string | null;
          platform: Database["public"]["Enums"]["post_platform"];
          platform_post_id: string | null;
          posted_at: string | null;
          property_id: string | null;
          updated_at: string;
        };
        Insert: {
          caption?: string | null;
          created_at?: string;
          id?: string;
          last_synced_at?: string | null;
          media_type?: Database["public"]["Enums"]["media_type"] | null;
          media_url?: string | null;
          metrics?: Json;
          mls_number_parsed?: string | null;
          permalink?: string | null;
          platform: Database["public"]["Enums"]["post_platform"];
          platform_post_id?: string | null;
          posted_at?: string | null;
          property_id?: string | null;
          updated_at?: string;
        };
        Update: {
          caption?: string | null;
          created_at?: string;
          id?: string;
          last_synced_at?: string | null;
          media_type?: Database["public"]["Enums"]["media_type"] | null;
          media_url?: string | null;
          metrics?: Json;
          mls_number_parsed?: string | null;
          permalink?: string | null;
          platform?: Database["public"]["Enums"]["post_platform"];
          platform_post_id?: string | null;
          posted_at?: string | null;
          property_id?: string | null;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "posts_property_id_fkey";
            columns: ["property_id"];
            isOneToOne: false;
            referencedRelation: "properties";
            referencedColumns: ["id"];
          },
        ];
      };
      profiles: {
        Row: {
          created_at: string;
          email: string;
          full_name: string | null;
          id: string;
          role: Database["public"]["Enums"]["user_role"];
          updated_at: string;
        };
        Insert: {
          created_at?: string;
          email: string;
          full_name?: string | null;
          id: string;
          role?: Database["public"]["Enums"]["user_role"];
          updated_at?: string;
        };
        Update: {
          created_at?: string;
          email?: string;
          full_name?: string | null;
          id?: string;
          role?: Database["public"]["Enums"]["user_role"];
          updated_at?: string;
        };
        Relationships: [];
      };
      properties: {
        Row: {
          address: string | null;
          agent_email: string | null;
          agent_name: string | null;
          city: string | null;
          created_at: string;
          hero_image_url: string | null;
          id: string;
          list_price: number | null;
          listing_date: string | null;
          mls_number: string;
          notes: string | null;
          state: string | null;
          status: Database["public"]["Enums"]["property_status"];
          updated_at: string;
          zip: string | null;
        };
        Insert: {
          address?: string | null;
          agent_email?: string | null;
          agent_name?: string | null;
          city?: string | null;
          created_at?: string;
          hero_image_url?: string | null;
          id?: string;
          list_price?: number | null;
          listing_date?: string | null;
          mls_number: string;
          notes?: string | null;
          state?: string | null;
          status?: Database["public"]["Enums"]["property_status"];
          updated_at?: string;
          zip?: string | null;
        };
        Update: {
          address?: string | null;
          agent_email?: string | null;
          agent_name?: string | null;
          city?: string | null;
          created_at?: string;
          hero_image_url?: string | null;
          id?: string;
          list_price?: number | null;
          listing_date?: string | null;
          mls_number?: string;
          notes?: string | null;
          state?: string | null;
          status?: Database["public"]["Enums"]["property_status"];
          updated_at?: string;
          zip?: string | null;
        };
        Relationships: [];
      };
      reports: {
        Row: {
          auto_send_at: string | null;
          created_at: string;
          generated_at: string | null;
          id: string;
          is_locked: boolean;
          property_id: string;
          report_token: string;
          sent_at: string | null;
          updated_at: string;
        };
        Insert: {
          auto_send_at?: string | null;
          created_at?: string;
          generated_at?: string | null;
          id?: string;
          is_locked?: boolean;
          property_id: string;
          report_token: string;
          sent_at?: string | null;
          updated_at?: string;
        };
        Update: {
          auto_send_at?: string | null;
          created_at?: string;
          generated_at?: string | null;
          id?: string;
          is_locked?: boolean;
          property_id?: string;
          report_token?: string;
          sent_at?: string | null;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "reports_property_id_fkey";
            columns: ["property_id"];
            isOneToOne: false;
            referencedRelation: "properties";
            referencedColumns: ["id"];
          },
        ];
      };
    };
    Views: { [_ in never]: never };
    Functions: { is_admin: { Args: never; Returns: boolean } };
    Enums: {
      credential_platform:
        | "facebook"
        | "instagram"
        | "tiktok"
        | "paragon_mls"
        | "bright_mls";
      media_type: "image" | "video" | "carousel" | "reel";
      post_platform: "facebook" | "instagram" | "tiktok";
      property_status: "active" | "pending" | "sold" | "expired";
      user_role: "admin" | "user";
    };
    CompositeTypes: { [_ in never]: never };
  };
};
