// Auto-generated by `supabase gen types typescript` (via Supabase MCP).
// Re-run after schema changes. Last regenerated: 2026-05-08 (post phase3 010-013 — agent category, post_groups, run_post_grouper, agent_name).

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      api_credentials: {
        Row: {
          created_at: string
          credentials: Json
          id: string
          is_active: boolean
          last_validated_at: string | null
          platform: Database["public"]["Enums"]["credential_platform"]
          updated_at: string
        }
        Insert: {
          created_at?: string
          credentials?: Json
          id?: string
          is_active?: boolean
          last_validated_at?: string | null
          platform: Database["public"]["Enums"]["credential_platform"]
          updated_at?: string
        }
        Update: {
          created_at?: string
          credentials?: Json
          id?: string
          is_active?: boolean
          last_validated_at?: string | null
          platform?: Database["public"]["Enums"]["credential_platform"]
          updated_at?: string
        }
        Relationships: []
      }
      notifications: {
        Row: {
          created_at: string
          id: string
          is_read: boolean
          message: string | null
          metadata: Json
          title: string
          type: string
          updated_at: string
          user_id: string
        }
        Insert: {
          created_at?: string
          id?: string
          is_read?: boolean
          message?: string | null
          metadata?: Json
          title: string
          type: string
          updated_at?: string
          user_id: string
        }
        Update: {
          created_at?: string
          id?: string
          is_read?: boolean
          message?: string | null
          metadata?: Json
          title?: string
          type?: string
          updated_at?: string
          user_id?: string
        }
        Relationships: []
      }
      post_groups: {
        Row: {
          category: Database["public"]["Enums"]["post_category"] | null
          created_at: string
          group_method: Database["public"]["Enums"]["post_group_method"]
          id: string
          is_locked: boolean
          posted_date: string | null
          property_id: string | null
          representative_caption: string | null
          representative_thumbnail: string | null
          updated_at: string
        }
        Insert: {
          category?: Database["public"]["Enums"]["post_category"] | null
          created_at?: string
          group_method?: Database["public"]["Enums"]["post_group_method"]
          id?: string
          is_locked?: boolean
          posted_date?: string | null
          property_id?: string | null
          representative_caption?: string | null
          representative_thumbnail?: string | null
          updated_at?: string
        }
        Update: {
          category?: Database["public"]["Enums"]["post_category"] | null
          created_at?: string
          group_method?: Database["public"]["Enums"]["post_group_method"]
          id?: string
          is_locked?: boolean
          posted_date?: string | null
          property_id?: string | null
          representative_caption?: string | null
          representative_thumbnail?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "post_groups_property_id_fkey"
            columns: ["property_id"]
            isOneToOne: false
            referencedRelation: "properties"
            referencedColumns: ["id"]
          },
        ]
      }
      post_metrics_daily: {
        Row: {
          avg_watch_time_sec: number | null
          captured_at: string
          captured_date: string
          comments: number | null
          completion_rate: number | null
          engagement_rate: number | null
          follows: number | null
          impressions: number | null
          likes: number | null
          link_clicks: number | null
          plays: number | null
          post_id: string
          profile_visits: number | null
          raw_payload: Json
          reach: number | null
          saves: number | null
          shares: number | null
        }
        Insert: {
          avg_watch_time_sec?: number | null
          captured_at?: string
          captured_date?: string
          comments?: number | null
          completion_rate?: number | null
          engagement_rate?: number | null
          follows?: number | null
          impressions?: number | null
          likes?: number | null
          link_clicks?: number | null
          plays?: number | null
          post_id: string
          profile_visits?: number | null
          raw_payload?: Json
          reach?: number | null
          saves?: number | null
          shares?: number | null
        }
        Update: {
          avg_watch_time_sec?: number | null
          captured_at?: string
          captured_date?: string
          comments?: number | null
          completion_rate?: number | null
          engagement_rate?: number | null
          follows?: number | null
          impressions?: number | null
          likes?: number | null
          link_clicks?: number | null
          plays?: number | null
          post_id?: string
          profile_visits?: number | null
          raw_payload?: Json
          reach?: number | null
          saves?: number | null
          shares?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "post_metrics_daily_post_id_fkey"
            columns: ["post_id"]
            isOneToOne: false
            referencedRelation: "posts"
            referencedColumns: ["id"]
          },
        ]
      }
      posts: {
        Row: {
          agent_name: string | null
          audience: Json
          caption: string | null
          category: Database["public"]["Enums"]["post_category"] | null
          created_at: string
          group_id: string | null
          hashtags: string[]
          id: string
          last_synced_at: string | null
          link_method: Database["public"]["Enums"]["post_link_method"] | null
          media_type: Database["public"]["Enums"]["media_type"] | null
          media_url: string | null
          metrics: Json
          mls_number_parsed: string | null
          permalink: string | null
          platform: Database["public"]["Enums"]["post_platform"]
          platform_post_id: string | null
          posted_at: string | null
          property_id: string | null
          thumbnail_url: string | null
          updated_at: string
        }
        Insert: {
          agent_name?: string | null
          audience?: Json
          caption?: string | null
          category?: Database["public"]["Enums"]["post_category"] | null
          created_at?: string
          group_id?: string | null
          hashtags?: string[]
          id?: string
          last_synced_at?: string | null
          link_method?: Database["public"]["Enums"]["post_link_method"] | null
          media_type?: Database["public"]["Enums"]["media_type"] | null
          media_url?: string | null
          metrics?: Json
          mls_number_parsed?: string | null
          permalink?: string | null
          platform: Database["public"]["Enums"]["post_platform"]
          platform_post_id?: string | null
          posted_at?: string | null
          property_id?: string | null
          thumbnail_url?: string | null
          updated_at?: string
        }
        Update: {
          agent_name?: string | null
          audience?: Json
          caption?: string | null
          category?: Database["public"]["Enums"]["post_category"] | null
          created_at?: string
          group_id?: string | null
          hashtags?: string[]
          id?: string
          last_synced_at?: string | null
          link_method?: Database["public"]["Enums"]["post_link_method"] | null
          media_type?: Database["public"]["Enums"]["media_type"] | null
          media_url?: string | null
          metrics?: Json
          mls_number_parsed?: string | null
          permalink?: string | null
          platform?: Database["public"]["Enums"]["post_platform"]
          platform_post_id?: string | null
          posted_at?: string | null
          property_id?: string | null
          thumbnail_url?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "posts_group_id_fkey"
            columns: ["group_id"]
            isOneToOne: false
            referencedRelation: "post_groups"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "posts_property_id_fkey"
            columns: ["property_id"]
            isOneToOne: false
            referencedRelation: "properties"
            referencedColumns: ["id"]
          },
        ]
      }
      profiles: {
        Row: {
          created_at: string
          email: string
          full_name: string | null
          id: string
          role: Database["public"]["Enums"]["user_role"]
          updated_at: string
        }
        Insert: {
          created_at?: string
          email: string
          full_name?: string | null
          id: string
          role?: Database["public"]["Enums"]["user_role"]
          updated_at?: string
        }
        Update: {
          created_at?: string
          email?: string
          full_name?: string | null
          id?: string
          role?: Database["public"]["Enums"]["user_role"]
          updated_at?: string
        }
        Relationships: []
      }
      properties: {
        Row: {
          address: string | null
          agent_email: string | null
          agent_name: string | null
          city: string | null
          created_at: string
          hero_image_url: string | null
          id: string
          list_price: number | null
          listing_date: string | null
          mls_number: string
          notes: string | null
          state: string | null
          status: Database["public"]["Enums"]["property_status"]
          updated_at: string
          zip: string | null
        }
        Insert: {
          address?: string | null
          agent_email?: string | null
          agent_name?: string | null
          city?: string | null
          created_at?: string
          hero_image_url?: string | null
          id?: string
          list_price?: number | null
          listing_date?: string | null
          mls_number: string
          notes?: string | null
          state?: string | null
          status?: Database["public"]["Enums"]["property_status"]
          updated_at?: string
          zip?: string | null
        }
        Update: {
          address?: string | null
          agent_email?: string | null
          agent_name?: string | null
          city?: string | null
          created_at?: string
          hero_image_url?: string | null
          id?: string
          list_price?: number | null
          listing_date?: string | null
          mls_number?: string
          notes?: string | null
          state?: string | null
          status?: Database["public"]["Enums"]["property_status"]
          updated_at?: string
          zip?: string | null
        }
        Relationships: []
      }
      report_deliveries: {
        Row: {
          channel: Database["public"]["Enums"]["delivery_channel"]
          created_at: string
          id: string
          recipient_email: string | null
          recipient_name: string | null
          report_id: string
          sent_at: string | null
          share_token: string
          status: Database["public"]["Enums"]["delivery_status"]
          updated_at: string
          view_count: number
          viewed_at: string | null
        }
        Insert: {
          channel?: Database["public"]["Enums"]["delivery_channel"]
          created_at?: string
          id?: string
          recipient_email?: string | null
          recipient_name?: string | null
          report_id: string
          sent_at?: string | null
          share_token: string
          status?: Database["public"]["Enums"]["delivery_status"]
          updated_at?: string
          view_count?: number
          viewed_at?: string | null
        }
        Update: {
          channel?: Database["public"]["Enums"]["delivery_channel"]
          created_at?: string
          id?: string
          recipient_email?: string | null
          recipient_name?: string | null
          report_id?: string
          sent_at?: string | null
          share_token?: string
          status?: Database["public"]["Enums"]["delivery_status"]
          updated_at?: string
          view_count?: number
          viewed_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "report_deliveries_report_id_fkey"
            columns: ["report_id"]
            isOneToOne: false
            referencedRelation: "reports"
            referencedColumns: ["id"]
          },
        ]
      }
      reports: {
        Row: {
          audience: Json
          auto_send_at: string | null
          created_at: string
          generated_at: string | null
          id: string
          is_locked: boolean
          kpis: Json
          narrative: Json
          period_end: string | null
          period_start: string | null
          post_ids: string[]
          property_id: string
          report_token: string
          sent_at: string | null
          updated_at: string
        }
        Insert: {
          audience?: Json
          auto_send_at?: string | null
          created_at?: string
          generated_at?: string | null
          id?: string
          is_locked?: boolean
          kpis?: Json
          narrative?: Json
          period_end?: string | null
          period_start?: string | null
          post_ids?: string[]
          property_id: string
          report_token: string
          sent_at?: string | null
          updated_at?: string
        }
        Update: {
          audience?: Json
          auto_send_at?: string | null
          created_at?: string
          generated_at?: string | null
          id?: string
          is_locked?: boolean
          kpis?: Json
          narrative?: Json
          period_end?: string | null
          period_start?: string | null
          post_ids?: string[]
          property_id?: string
          report_token?: string
          sent_at?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "reports_property_id_fkey"
            columns: ["property_id"]
            isOneToOne: false
            referencedRelation: "properties"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      is_admin: { Args: never; Returns: boolean }
      run_auto_linker: {
        Args: never
        Returns: {
          matched_addr_full: number
          matched_addr_partial: number
          matched_mls: number
        }[]
      }
      run_post_grouper: {
        Args: never
        Returns: {
          groups_created: number
          posts_assigned: number
        }[]
      }
    }
    Enums: {
      credential_platform:
        | "facebook"
        | "instagram"
        | "tiktok"
        | "paragon_mls"
        | "bright_mls"
      delivery_channel: "email" | "link"
      delivery_status: "pending" | "sent" | "viewed"
      media_type: "image" | "video" | "carousel" | "reel"
      post_category:
        | "property"
        | "agent"
        | "educational"
        | "marketing"
        | "community"
        | "sold"
        | "other"
      post_group_method: "auto" | "manual"
      post_link_method:
        | "manual"
        | "auto_mls"
        | "auto_address_full"
        | "auto_address_partial"
      post_platform: "facebook" | "instagram" | "tiktok"
      property_status: "active" | "pending" | "sold" | "expired"
      user_role: "admin" | "user"
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {
      credential_platform: [
        "facebook",
        "instagram",
        "tiktok",
        "paragon_mls",
        "bright_mls",
      ],
      delivery_channel: ["email", "link"],
      delivery_status: ["pending", "sent", "viewed"],
      media_type: ["image", "video", "carousel", "reel"],
      post_category: [
        "property",
        "agent",
        "educational",
        "marketing",
        "community",
        "sold",
        "other",
      ],
      post_group_method: ["auto", "manual"],
      post_link_method: [
        "manual",
        "auto_mls",
        "auto_address_full",
        "auto_address_partial",
      ],
      post_platform: ["facebook", "instagram", "tiktok"],
      property_status: ["active", "pending", "sold", "expired"],
      user_role: ["admin", "user"],
    },
  },
} as const
